### ISSUE TITLE
Update FireOS version

### ISSUE THREAD

**Issue by CapitanoNemo7** [visnkmr/backgroundappslist#265]
Please, update app for fireOS devices.
It's so useful on my Fire TV stick☺️🙏

Thanks for your great work 👏👍

**Comment by visnkmr** [comment]
Hey, an update should already be available on Fire TV's appstore (Available since 15 days ago).The appstores may not auto-update the app, so you need to check manually.
Latest version on:

Fire TV, Tablet appstore is 1.3A12I,
Google play version is 1.3G10I.

If no updates are available for you, sometimes they do take some time to roll out updates based on region, I'll look into what can be done to prevent these in the future.

**Comment by CapitanoNemo7** [comment]
Sorry, I didn't try to uninstall app before check in the Amazon appstore..

with the old app installed the store does not report available updates... and clicking on it opens the one already installed...

Thanks, next time I will uninstall the old one before checking the new version 🙂

**Comment by visnkmr** [comment]
Hey, 
Glad that the app works for you now. 
This is not your mistake, its a mistake by the appstore it should have auto updated the app long ago. 
Thanks for reporting the issue.
