### ISSUE TITLE
FireStick update

### ISSUE THREAD

**Issue by alysynn** [visnkmr/backgroundappslist#268]
Hey- just tried to update on my FireStick via native Amazon App Store, but it is still downloading the previous version.

(I used Downloader to grab an apk and new version installed and app is working fine. Just thought I'd mention the firestick thing).

**Comment by visnkmr** [comment]
Hey, Thanks for reporting.
An update should already have been available on Fire TV's appstore (Available since 15 days ago). Sometimes they do take some time to roll out updates based on region, I'll look into what can be done to prevent these in the future.
Latest version on:

Fire TV, Tablet appstore is 1.3A12I,
Google play version is 1.3G10I.
